### ISSUE TITLE
shopify-express is not the latest version

### ISSUE THREAD

**Issue by vimagick** [gregorybesson/shopify-sales-channel#1]
Hello

I'm trying to run your code as shopify sales channel.
Notice that `shopify-express` is not the latest version.

There're some issues, for example:

- https://github.com/gregorybesson/shopify-express/blob/master/middleware/webhooks.js#L10-L20
    `JSON.stringify(JSON.parse('0.0')) != '0.0'`

- https://github.com/gregorybesson/shopify-express/blob/master/strategies/RedisStrategy.js#L15
    `clientToken` => `accessToken`

It seems no such issues in the latest version of `shopify-express` .
Is there any plan to upgrade `shopify-express` to the latest?
Thanks!

**Comment by gregorybesson** [comment]
Hello @vimagick, this version is behind the official version : I've sent PR to them and the fixes of this repo have been included in the new version. So you should use the official version :)

have a nice day.

**Comment by vimagick** [comment]
Thank you!
